--SEQUENCE 란?
--P KEY를 생성하는 귀차니즘을 해결하기 위한 키워드
DESC USER_SEQUENCES;

SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, CYCLE_FLAG
FROM USER_SEQUENCES; --시퀀스 확인할수 있는 테이블
-- 현재 아무것도 없다.

CREATE SEQUENCE DEPT_DEPTNO_SEQ
INCREMENT BY 10
START WITH 10;
--CYCLE의 디폴트는 N
--CURRVAL 현재값
--NEXTVAL 다음값

SELECT DEPT_DEPTNO_SEQ.NEXTVAL FROM DUAL; --한번실행하면 영구히 값이 증가한다. 10,20,30...

SELECT DEPT_DEPTNO_SEQ.CURRVAL FROM DUAL; --만들어진 시퀀스 번호를 참조할때
--새로운 시퀀스 생성
CREATE SEQUENCE EMP_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 1000000;

SELECT EMP_SEQ.CURRVAL FROM DUAL;
--시퀀스 삭제

DROP SEQUENCE DEPT_DEPTNO_SEQ;
DROP TABLE EMP01;
CREATE TABLE EMP01(
			EMPNO NUMBER(4) PRIMARY KEY,
			ENAME VARCHAR2(10),
			HIREDATE DATE
			);
			

INSERT INTO EMP01
VALUES(EMP_SEQ.NEXTVAL,'JULIA',SYSDATE); --시퀀스로 삽입

SELECT *FROM EMP01; --확인

CREATE SEQUENCE DEPT_DEPTNO_SEQ
START WITH 10
INCREMENT BY 10
MAXVALUE 30;

SELECT DEPT_DEPTNO_SEQ.NEXTVAL FROM DUAL; -- 30이상이면 MAXVALUE를 넘고 NOCYCLE이기 때문에 에러가 발생한다.
--시퀀스에 MAXVALUE를 변경한다.
ALTER SEQUENCE DEPT_DEPTNO_SEQ
MAXVALUE 1000;
--이후 잘 동작한다.

SELECT *
FROM USER_SEQUENCES;